### ISSUE TITLE
Not able to figure out with Dayun Zig Z1+

### ISSUE THREAD

**Issue by KWIKalamzoo** [minerstat/minerstat-asic-hub#1]
Here is the trace.

wget -O install.sh http://static.minerstat.farm/github/install.sh && chmod 777 *.sh && sh install.sh replaced_Key workername_created_in_portal
--2018-10-22 21:24:36--  http://static.minerstat.farm/github/install.sh
Resolving static.minerstat.farm (static.minerstat.farm)... 94.177.199.253
Connecting to static.minerstat.farm (static.minerstat.farm)|94.177.199.253|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4214 (4.1K) [text/plain]
Saving to: ‘install.sh’

install.sh          100%[===================>]   4.12K  --.-KB/s    in 0.001s  

2018-10-22 21:24:37 (7.27 MB/s) - ‘install.sh’ saved [4214/4214]

--------- MINERSTAT ASIC HUB (INSTALL) -----------
grep: error.log: No such file or directory
CURL IS OK!
install.sh: 82: install.sh: screen: not found
install.sh: 83: install.sh: screen: not found
install.sh: 89: cd: can't cd to /var/www/html/resources/minerstat
rm: cannot remove 'minerstat.sh': No such file or directory
sed: can't read /usr/bin/compile_time: No such file or directory
install.sh: 99: install.sh: curl: not found
---- USER -----
chmod: cannot access 'minerstat.sh': No such file or directory
rm: cannot remove 'minerstat.sh': No such file or directory
chmod: cannot access 'minerstat.sh': No such file or directory
TOKEN=d1f9d07c
WORKER=MDAYUN
install.sh: 125: install.sh: curl: not found
rm: chmod: cannot access 'runmeonboot'cannot remove 'runmeonboot': No such file or directory: No such file or directory

insserv: warning: script 'K01minerstat' missing LSB tags and overrides
insserv: warning: script 'minerstat' missing LSB tags and overrides
{
    "pools": [
        {
            "url": "stratum+tcp:\/\/192.168.1.147:4996",
            "user": "x",
            "pass": "x"
        },
        {
            "url": "stratum+tcp:\/\/192.168.1.175:8888",
            "user": "1",
            "pass": "3"
        },
        {
            "url": "stratum+tcp:\/\/192.168.1.175:8888#xnsub",
            "user": "2",
            "pass": "3"
        }
    ],
    "api-allow": "W:0\/0",
    "api-description": "cgminer 4.11.1",
    "api-listen": true,
    "api-mcast-addr": "224.0.0.75",
    "api-mcast-code": "FTW",
    "api-mcast-des": "",
    "api-mcast-port": "4028",
    "api-network": true,
    "api-port": "4028",
    "expiry": "120",
    "failover-switch-delay": "300",
    "log": "5",
    "queue": "9999",
    "scan-time": "60",
    "shares": "0",
    "lyra2rev2-clk": "925",
    "lyra2rev2-vol": "0",
    "lyra2rev2-asic-x": "4",
    "lyra2rev2-asic-y": "24",
    "lyra2rev2-asic-num": "50",
    "lyra2rev2-cutofftemperature": "50",
    "lyra2rev2-cutofffanspeedin": "100",
    "lyra2rev2-cutofffanspeedout": "100",
    "lyra2rev2-restarthashrate": "7",
    "lyra2rev2-restartfailedcount": "100",
    "lyra2rev2-fan": "LV1",
    "lyra2rev2-check-testnonce": true,
    "lyra2rev2-machine-type": "1",
    "lyra2rev2-scan-serial": "\/dev\/ttyS3",
    "lyra2rev2-restartenable": false,
    "lyra2rev2-cutoffenable": false
}
install.sh: 155: install.sh: curl: not found
CONFIG POST => 
Installation => DONE
Notice => You can check the process running with: screen -list
sh: 0: Can't open runmeonboot

**Comment by coinscrow** [comment]
Supported and tested ASICs:

Antminer A3
Antminer B3
Antminer D3 / D3 Blissz
Antminer E3
Antminer L3+ / L3++
Antminer S1-S9, S9i, S9j (All firmware)
Antminer T9 / T9+
Antminer X3
Antminer Z9 / Z9-Mini

Currently Dayun not on the supported List of the HUB.
Dayun only works with ASIC Node.
